default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: my-secret-pw
  host: 127.0.0.1

development:
  <<: *default
  database: rails_app

test:
  <<: *default
  database: rails_app

production:
  <<: *default
  database: rails_app